# Generated by Django 2.0.4 on 2018-04-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20180425_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
