# Generated by Django 2.0.4 on 2018-04-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20180425_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position_title',
            new_name='title',
        ),
    ]
