# Generated by Django 2.0.4 on 2018-04-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20180426_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='title',
            new_name='position_title',
        ),
    ]
